### ISSUE TITLE
Current day is not shown

### ISSUE THREAD

**Issue by Mihai-B** [jackyliang/Material-Design-For-Full-Calendar#4]
I am not sure if you are aware, but the current day header text is not shown. Is this intended ?

**Comment by jackyliang** [comment]
@Mihai-B I'm not sure if the CSS controls the header text visibility or not (might be part of the library configs than the CSS), but for my uses, not showing the current day header text was intended. As for my CSS, I specifically removed the today border and color in this [line](https://github.com/jackyliang/Material-Design-For-Full-Calendar/blob/master/_materialFullCalendar.scss#L41). For your uses, feel free to remove that block.

**Comment by Mihai-B** [comment]
Yea I figured that is the line.
The problem is that if I remove the line I see the highlighted column, and I also hate that. Will try and find a work arround for this.
Thnx for the info anyhow

**Comment by jackyliang** [comment]
You could probably change the color of the column if anything. Just play around with the inspector (which is what I did). Glad this library is helpful to you!
